name: Android builds

on:
  push:
    branches: [master]

jobs:
  build_android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7'
      - run: flutter pub get
      - run: "${GITHUB_WORKSPACE}/scripts/generate-keystore.sh GithubAction"
      - run: flutter build apk
      - run: flutter build appbundle
